repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: double-quote-string-fixer
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
    exclude: 'migrations|.*config.py|.*main.py|.*settings.py'

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    exclude: 'migrations'

- repo: https://github.com/psf/black
  rev: 23.9.0
  hooks:
  - id: black
    args: [--skip-string-normalization]
    exclude: (migrations|settings)
    language_version: python3.10


- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yamlgit
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
