# Generated by Django 4.2 on 2024-03-13 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0, message='Цена товара не может быть отрицательной')], verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', verbose_name='Статус заказа')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заказа')),
                ('time_accepted', models.DateTimeField(auto_now=True, verbose_name='Время подтверждения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0, message='Цена товара не может быть отрицательной')], verbose_name='Цена товара')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Доступное количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/images/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0, message='Цена товара не может быть отрицательной')], verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('pending', 'В процессе оплаты'), ('accepted', 'Оплачено'), ('rejected', 'Не оплачено')], default='pending', verbose_name='Статус оплаты')),
                ('type', models.CharField(choices=[('pin', 'Оплата картой'), ('cash', 'Оплата наличными')], default='pin', verbose_name='Тип оплаты')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='shop.OrderProduct', to='shop.product', verbose_name='Товары'),
        ),
    ]
